/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
 * Generated on: 01-Sep-2020 14:39:54
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 175
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\Program Files\MATLAB\R2016a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 175;
const short B[175] = {
      -16,      9,     16,     27,     43,     62,     83,    104,    123,
      139,    149,    151,    145,    130,    106,     74,     38,      0,
      -37,    -68,    -91,   -103,   -102,    -88,    -63,    -28,     11,
       50,     85,    110,    123,    120,    101,     67,     23,    -27,
      -76,   -119,   -148,   -161,   -152,   -123,    -76,    -16,     51,
      116,    170,    206,    217,    200,    155,     86,      1,    -92,
     -179,   -250,   -293,   -301,   -269,   -199,    -95,     31,    165,
      289,    387,    444,    446,    388,    271,    102,   -102,   -320,
     -526,   -689,   -784,   -785,   -677,   -450,   -107,    340,    867,
     1442,   2026,   2579,   3060,   3433,   3668,   3749,   3668,   3433,
     3060,   2579,   2026,   1442,    867,    340,   -107,   -450,   -677,
     -785,   -784,   -689,   -526,   -320,   -102,    102,    271,    388,
      446,    444,    387,    289,    165,     31,    -95,   -199,   -269,
     -301,   -293,   -250,   -179,    -92,      1,     86,    155,    200,
      217,    206,    170,    116,     51,    -16,    -76,   -123,   -152,
     -161,   -148,   -119,    -76,    -27,     23,     67,    101,    120,
      123,    110,     85,     50,     11,    -28,    -63,    -88,   -102,
     -103,    -91,    -68,    -37,      0,     38,     74,    106,    130,
      145,    151,    149,    139,    123,    104,     83,     62,     43,
       27,     16,      9,    -16
};
